name: Crawl and extract text
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: raw-text-chunks-2024-04-05
    required: true
  - name: textchunksize
    inputType: FreeText
    description: 200
    defaultValue: 1000
    required: false
  - name: textoverlapsize
    inputType: FreeText
    description: ''
    defaultValue: 200
    required: false
  - name: use_local_crawl_pickle
    inputType: FreeText
    description: ''
    defaultValue: False
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
