name: mongodb-sink
language: Python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: slack-enriched
    required: false
  - name: URI
    inputType: Secret
    defaultValue: URI-key
    required: false
  - name: PROJECT_ID
    inputType: FreeText
    defaultValue: portalanalytics-391408
    required: false
  - name: DATASET_ID
    inputType: FreeText
    defaultValue: community-slack
    required: false
  - name: DATASET_LOCATION
    inputType: FreeText
    defaultValue: europe-west3
    required: false
  - name: TABLE_NAME
    inputType: FreeText
    defaultValue: threads
    required: false
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: big-query-sink-v1
    required: false
  - name: MAX_QUEUE_SIZE
    inputType: FreeText
    defaultValue: 100
    required: false
  - name: COLLECTION_NAME
    inputType: FreeText
    defaultValue: slack_community
    required: false
  - name: DATABASE_NAME
    inputType: FreeText
    defaultValue: SlackCommunity
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
