name: slack-history-batch-load
language: Python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: slack-raw-history
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
